import { ArcanoMineral } from './types';

export const ARCANA_DATA: ArcanoMineral[] = [
  {
    number: 0,
    roman: "0",
    arcanaName: "Il Matto",
    mineralName: "Quarzo Ialino",
    subTitle: "Cristallo di Rocca",
    formula: "SiO₂",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato (Ossido)",
    colorGradient: "from-slate-200/20 via-sky-100/10 to-blue-200/5",
    accentColor: "#e0f2fe",
    scientificBasis: "Trasparente e privo di impurità cromatiche, contiene in potenza l'intero spettro della luce visibile. Incarna la tabula rasa, l'inizio assoluto e l'energia indifferenziata.",
    opticsPhysical: "Trasparenza ottica completa, elevata piezoelettricità, rifrazione limpida senza assorbimento selettivo.",
    materiale: "Biossido di silicio puro cristallizzato nel sistema trigonale. È caratterizzato da una durezza Mohs pari a 7 e dall'assenza di sfaldatura, con frattura concoide. Presenta spiccate proprietà piezoelettriche, in grado di generare cariche elettriche in risposta a sollecitazioni meccaniche.",
    spirituale: "Rappresenta l'Unità primordiale, la luce bianca indifferenziata che precede la scomposizione dello spettro visibile. È il veicolo dello Spirito che scende nella materia senza lasciarsi corrompere, mantenendo pura l'intenzione originaria del viaggio.",
    immaginale: "Il Daimon della tabula rasa. Nella psicologia immaginale rappresenta lo stato di 'vuoto fertile' (Kenosis) e la purezza della percezione non filtrata dai costrutti dell'Io. È lo specchio dell'Anima Mundi prima della polarizzazione, il corpo di luce trasparente.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=600&q=80",
    tags: ["Potenziale Puro", "Kenosis", "Piezoelettrico", "Luce Bianca"],
    chakraName: "Sahasrara - Chakra della Corona (Settimo Chakra)",
    chakraMotivazione: "Il Quarzo Ialino è pura luce traslucida che riflette l'unità primordiale e lo spettro cromatico intero, proprio come Sahasrara accoglie l'infinito spirituale e dissolve i confini dell'ego.",
    chakraPuntiForza: "Apertura mentale assoluta, sintonizzazione cosmica, percezione senza filtri e potenziale spirituale illimitato.",
    chakraPuntiDebolezza: "Disconnessione dalla realtà materiale, confusione mentale, instabilità emotiva e fuga dalla concretezza (radicamento assente).",
    chakraEquilibrio: "Meditazione silenziosa tenendo un cristallo di rocca sulla corona; visualizzare una luce bianca purissima che scende lungo la colonna fino alla terra."
  },
  {
    number: 1,
    roman: "I",
    arcanaName: "Il Bagatto",
    mineralName: "Pirite",
    subTitle: "Solfuro di Ferro",
    formula: "FeS₂",
    system: "Cubico",
    hardness: 6.5,
    category: "Solfuro",
    colorGradient: "from-amber-400/20 via-yellow-600/10 to-amber-200/5",
    accentColor: "#f59e0b",
    scientificBasis: "Solfuro di ferro con perfetti cristalli cubici dai riflessi dorati. Rappresenta la capacità di organizzare la materia grezza con precisione geometrica e la scintilla dell'azione creatrice.",
    opticsPhysical: "Lucentezza metallica elevata, scarsa conducibilità elettrica a freddo, genesi prevalentemente idrotermale.",
    materiale: "Bisolfuro di ferro (FeS₂). Cristallizza nel sistema cubico, formando spesso perfetti cubi striati o pentagonododecaedri (piritoedri). Con una durezza Mohs di 6-6.5, è un minerale pesante con lucentezza metallica speculare dorata.",
    spirituale: "Rappresenta il Logos ordinatore, il principio della Volontà che modella il caos amorfo terrestre in forme perfette. È il fuoco concentrato nella terra, la scintilla d'oro che risiede nei recessi profondi dell'inconscio.",
    immaginale: "Il Daimon dell'Alchimista e del Fabbro. Simboleggia il potere immaginale di tradurre l'ispirazione invisibile in una struttura tridimensionale tangibile e definita. È l'archetipo dell'inizio dell'Opera, dove lo spirito si fa architettura d'oro.",
    crystalShape: "cubic",
    imageUrl: "https://images.unsplash.com/photo-1614362145802-53b708304959?auto=format&fit=crop&w=600&q=80",
    tags: ["Volontà", "Struttura Cubica", "Fuoco della Terra", "Inizio Opera"],
    chakraName: "Manipura - Chakra del Plesso Solare (Terzo Chakra)",
    chakraMotivazione: "La Pirite, con la sua lucentezza dorata metallica e geometria ferrea, incarna l'energia del sole e del fuoco, catalizzando l'azione ordinatrice del Bagatto nel plesso solare.",
    chakraPuntiForza: "Forza di volontà indomita, focalizzazione mentale infallibile, determinazione e chiarezza d'intenti nel plasmare la materia.",
    chakraPuntiDebolezza: "Tendenza all'iper-controllo, egocentrismo, irritabilità, ansia da prestazione e rigidità mentale.",
    chakraEquilibrio: "Eseguire visualizzazioni di sfere dorate radianti dal plesso; respirazione diaframmatica consapevole tenendo una pirite sull'addome."
  },
  {
    number: 2,
    roman: "II",
    arcanaName: "La Papessa",
    mineralName: "Pietra di Luna",
    subTitle: "Adularia",
    formula: "KAlSi₃O₈",
    system: "Monoclinico",
    hardness: 6,
    category: "Silicato (Feldspato)",
    colorGradient: "from-indigo-300/20 via-slate-400/10 to-purple-300/5",
    accentColor: "#c084fc",
    scientificBasis: "Esibisce il fenomeno dell'adularescenza: un riflesso azzurrato fluttuante generato dall'interferenza ottica tra strati alternati microscopici di albite e ortoclasio. Simboleggia il mistero svelato gradualmente.",
    opticsPhysical: "Gatteggiamento soffuso, riflessi blu-argentei dovuti all'effetto ottico Tyndall su microstrutture.",
    materiale: "Varietà di feldspato potassico (ortoclasio o adularia). Cristallizza nel sistema monoclinico. Esibisce una sfaldatura perfetta in due direzioni a 90° e una durezza di 6. Il suo tipico chiarore fluttuante è dovuto alla separazione microscopica dei piani cristallini durante il raffreddamento.",
    spirituale: "Custode delle acque sotterranee e della rivelazione silenziosa. Incarna la Sapienza non detta, lo specchio lunare che riflette la luce solare rendendola sopportabile per l'occhio interiore, il velo del tempio che protegge i misteri.",
    immaginale: "Il Daimon della Soglia e dell'Inconscio. Rappresenta la percezione dei mondi sottili attraverso l'immaginazione passiva e ricettiva. È l'Anima che apprende nel silenzio e nel sogno, leggendo la trama nascosta dei fenomeni naturali.",
    crystalShape: "monoclinic",
    imageUrl: "https://images.unsplash.com/photo-1551269901-5c5e14c25df7?auto=format&fit=crop&w=600&q=80",
    tags: ["Intuizione", "Adularescenza", "Sapienza Silente", "Feldspato"],
    chakraName: "Ajna - Chakra del Terzo Occhio (Sesto Chakra)",
    chakraMotivazione: "L'adularescenza della Pietra di Luna, specchio di sogni e misteri celati, vibra intensamente con l'intuizione e la visione extrasensoriale di Ajna.",
    chakraPuntiForza: "Intuizione profonda, ricettività spirituale eccezionale, percezione sottile e connessione con l'inconscio.",
    chakraPuntiDebolezza: "Disorientamento, isolamento freddo, incapacità di agire nel mondo pratico e tendenza ad perdersi in illusioni fantasiose.",
    chakraEquilibrio: "Posizionare una pietra di luna sulla fronte tra le sopracciglia durante un rilassamento serale; annotare i sogni sul diario dei Daimon."
  },
  {
    number: 3,
    roman: "III",
    arcanaName: "L'Imperatrice",
    mineralName: "Smeraldo",
    subTitle: "Berillo Verde",
    formula: "Be₃Al₂Si₆O₁₈:Cr",
    system: "Esagonale",
    hardness: 7.8,
    category: "Silicato (Ciclosilicato)",
    colorGradient: "from-emerald-500/20 via-green-600/10 to-teal-400/5",
    accentColor: "#10b981",
    scientificBasis: "Berillo arricchito da micro-tracce di cromo o vanadio che assorbono la luce rossa donando un verde lussureggiante. Incarna l'energia vitale generatrice, la fecondità della natura e lo splendore della crescita.",
    opticsPhysical: "Trasparenza pleocroica, stabilità chimica assoluta, inclusioni tipiche chiamate 'giardino'.",
    materiale: "Varietà verde del berillo, un silicato di berillio e alluminio. Cristallizza nel sistema esagonale, formando prismi regolari. Durezza elevatissima (7.5-8), ma fragile per la presenza di fessurazioni naturali interne (giardini dello smeraldo).",
    spirituale: "Rappresenta l'energy rigeneratrice dello Spirito della Natura (Viriditas). È la forza vitale divina che infonde bellezza e fertilità in tutta la creazione terrestre, la primavera interiore che fiorisce anche nel deserto.",
    immaginale: "Il Daimon della Fioritura e dell'Abbondanza. Simboleggia l'intelletto attivo immerso nell'Anima Mundi, capace di sognare forme lussureggianti e dar loro vita. È il volto verde della Grande Madre che accoglie, nutre ed esalta la vita.",
    crystalShape: "hexagonal",
    imageUrl: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=600&q=80",
    tags: ["Abbondanza", "Viriditas", "Sistema Esagonale", "Grande Madre"],
    chakraName: "Anahata - Chakra del Cuore (Quarto Chakra)",
    chakraMotivazione: "Il verde rigoglioso della Viriditas dello Smeraldo incarna la fioritura biologica ed emotiva dell'Imperatrice, ricollegandosi direttamente al centro dell'amore e dell'empatia cosmica.",
    chakraPuntiForza: "Amore incondizionato, abbondanza generativa, rigenerazione vitale e profonda compassione per tutti i regni viventi.",
    chakraPuntiDebolezza: "Possessività, dipendenza emotiva, paura del rifiuto e tendenza a soffocare l'altro con attenzioni eccessive.",
    chakraEquilibrio: "Passeggiare nei boschi respirando l'energia verde delle piante tenendo uno smeraldo al petto; recitare parole di amore ed accettazione di sé."
  },
  {
    number: 4,
    roman: "IV",
    arcanaName: "L'Imperatore",
    mineralName: "Diaspro Rosso",
    subTitle: "Quarzo Microcristallino",
    formula: "SiO₂ + Fe₂O₃",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato (Microcristallino)",
    colorGradient: "from-red-600/20 via-rose-800/10 to-orange-500/5",
    accentColor: "#ef4444",
    scientificBasis: "Quarzo microcristallino compatto e opaco, ricchissimo di ematite (ossido di ferro). La sua impareggiabile densità incarna la solidità, il radicamento terrestre, l'ordine stabile e la determinazione.",
    opticsPhysical: "Opacità totale dovuta alle microinclusione ferrose disperse nella matrice di silice.",
    materiale: "Roccia sedimentaria silicea formata da aggregati microcristallini di quarzo e calcedonio, intensamente pigmentata da ossidi di ferro (ematite) che le conferiscono il colore rosso mattone. Ha una durezza di 7 e una frattura concoide molto netta.",
    spirituale: "Rappresenta la Legge, il radicamento terrestre e la stabilità incrollabile del trono. È lo scudo che protegge i confini e la forza d'animo che non vacilla di fronte alla tempesta, canalizzando l'energia vitale per scopi giusti e ordinati.",
    immaginale: "Il Daimon del Custode e del Costruttore. È l'archetipo dell'autorità benevola che struttura lo spazio vitale, tracciando confini sani. Simboleggia il fuoco concentrato nella materia rocciosa, la certezza razionale che calma l'ansia dell'ignoto.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    tags: ["Radicamento", "Struttura Stabile", "Ossido di Ferro", "Legge"],
    chakraName: "Muladhara - Chakra della Radice (Primo Chakra)",
    chakraMotivazione: "La compattezza rocciosa del Diaspro Rosso ricca di ferro ematico risuona con la forza strutturante dell'Imperatore, ancorando solidamente il sistema osseo ed energetico alla terra.",
    chakraPuntiForza: "Radicamento possente, stabilità materiale, coraggio primordiale e senso di sicurezza incrollabile.",
    chakraPuntiDebolezza: "Dogmatismo ostinato, eccessiva rigidità autoritaria, rabbia territoriale e timore viscerale del caos.",
    chakraEquilibrio: "Praticare esercizi di grounding camminando scalzi a stretto contatto con il terreno naturale; tenere il diaspro rosso vicino al coccige durante la meditazione."
  },
  {
    number: 5,
    roman: "V",
    arcanaName: "Il Papa",
    mineralName: "Lapis Lazzuli",
    subTitle: "Roccia a Lazurite",
    formula: "Na₈[Al₆Si₆O₂₄]Sₙ + Pyrite/Calcite",
    system: "Cubico (Lazurite)",
    hardness: 5.5,
    category: "Roccia Metamorfica",
    colorGradient: "from-blue-600/20 via-indigo-900/10 to-yellow-500/5",
    accentColor: "#3b82f6",
    scientificBasis: "Roccia metamorfica in cui la lazurite azzurro-oltremare accoglie inclusioni dorate di pirite e bianche di calcite. Simboleggia l'unione organica di elementi opposti sotto una dottrina spirituale comune.",
    opticsPhysical: "Associazione di più minerali cristallini distinti, storicamente fonte del sacro blu oltremare.",
    materiale: "Non un singolo minerale, ma una roccia metamorfica formata principalmente da lazurite (un silicato contenente zolfo che dona il colore blu profondo), calcite (venature bianche) e pirite (pagliuzze metalliche dorate). Durezza 5.5, sensibile agli acidi.",
    spirituale: "Rappresenta l'insegnamento sacro, la connessione tra la terra e il cielo stellato (rappresentato dalle inclusioni di pirite dorata sul blu profondo). È la voce del saggio che traduce le leggi divine in precetti morali ed etici umani.",
    immaginale: "Il Daimon del Saggio e della Parola Sacra. Simboleggia l'unione rituale tra elementi diversi che trovano armonia in un disegno cosmico elevato. Traduce il profondo mistero dell'universo in una formula di comprensione comune.",
    crystalShape: "complex",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=600&q=80",
    tags: ["Insegnamento Sacro", "Cielo Stellato", "Lazurite", "Unione Opposti"],
    chakraName: "Vishuddha - Chakra della Gola (Quinto Chakra)",
    chakraMotivazione: "Il blu oltremare del Lapis Lazzuli rappresenta la verità sacra e la parola sacerdotale del Papa, ponendosi come ponte comunicativo perfetto per l'insegnamento dello spirito.",
    chakraPuntiForza: "Eloquenza ispirata, espressione etica profonda, capacità di unire concetti celesti e applicazioni pratiche.",
    chakraPuntiDebolezza: "Dogmatismo verbale, ipocrisia, timore di esprimere la verità interiore e l'uso manipolativo del verbo.",
    chakraEquilibrio: "Praticare il silenzio sacro alternato a canti devozionali o recitazione poetica; adagiare un lapis lazzuli sulla gola per sintonizzare il respiro."
  },
  {
    number: 6,
    roman: "VI",
    arcanaName: "Gli Amanti",
    mineralName: "Quarzo Rosa",
    subTitle: "Varietà di Quarzo",
    formula: "SiO₂ + Ti/Mn",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato",
    colorGradient: "from-rose-400/20 via-pink-600/10 to-red-300/5",
    accentColor: "#f472b6",
    scientificBasis: "Deve la sua tonalità rosa a finissime inclusioni fibrose dicroiche di dumortierite o titanio/manganese. Incarna la tensione attrattiva intermolecolare, la risonanza polare e l'unione dei simili.",
    opticsPhysical: "Trasparenza traslucida, pleocroismo debole, talvolta esibisce asterismo a sei punte in luce trasmessa.",
    materiale: "Varietà macrocristallina di biossido di silicio. Il colore rosa pallido o intenso è dovuto alla presenza di micro-inclusioni aghiformi orientate di una fase silicea affine alla dumortierite. Non forma quasi mai cristalli con facce euetrali.",
    spirituale: "Rappresenta l'amore universale, l'apertura del cuore e la grazia della scelta affettiva priva di egoismo. È la forza cosmica dell'attrazione molecolare e affettiva che lega gli elementi separati per dare vita a nuove e più complesse sintesi spirituali.",
    immaginale: "Il Daimon dell'Incontro e dell'Armonia Polare. È lo specchio dell'Anima che riconosce sé herself nell'altro, superando la scissione originaria. Rappresenta la tenerezza immaginale che ammorbidisce le durezze difensive dell'Io.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&w=600&q=80",
    tags: ["Scelta del Cuore", "Risonanza", "Dumortierite", "Amore Cosmico"],
    chakraName: "Anahata - Chakra del Cuore (Quarto Chakra)",
    chakraMotivazione: "Il Quarzo Rosa è il cristallo emblematico della risonanza affettiva ed emotiva. Mitiga le barriere del cuore supportando l'archetipo degli Amanti nella risonanza delle scelte d'amore.",
    chakraPuntiForza: "Empatia smisurata, capacità di perdono, pacificazione profonda e integrazione armoniosa del maschile e del femminile.",
    chakraPuntiDebolezza: "Estrema vulnerabilità emotiva, dipendenza affettiva simbiotica, timore del rifiuto e tendenza ad idealizzare le relazioni.",
    chakraEquilibrio: "Massaggiare l'area del petto con un quarzo rosa levigato riscaldato; visualizzare flussi di luce rosa che curano antiche ferite relazionali."
  },
  {
    number: 7,
    roman: "VII",
    arcanaName: "Il Carro",
    mineralName: "Ematite",
    subTitle: "Ossido di Ferro",
    formula: "Fe₂O₃",
    system: "Trigonale",
    hardness: 6,
    category: "Ossido",
    colorGradient: "from-slate-400/20 via-zinc-700/10 to-red-900/5",
    accentColor: "#94a3b8",
    scientificBasis: "Ossido di ferro pesante grigio-acciaio speculare all'esterno, ma con polvere e striscia rosso-sangue all'interno. Incarna la forza cinetica propulsiva, lo scudo e la determinazione metallica.",
    opticsPhysical: "Riflettanza metallica estrema, elevatissimo peso specifico (5.26 g/cm³), magnetismo assente a freddo.",
    materiale: "Sesquiossido di ferro (Fe₂O₃). Cristallizza nel sistema trigonale. È caratterizzata da una lucentezza metallica grigia lucida, ma la sua polvere e la sua traccia su porcellana ruvida sono costantemente di un colore rosso sangue intenso (da cui il nome ematite).",
    spirituale: "Rappresenta la volontà focalizzata del guerriero spirituale che cavalca la materia. È il sangue di ferro che scorre nelle vene della terra, dando la forza vitale e il coraggio per conquistare la propria indipendenza spirituale senza perdersi.",
    immaginale: "Il Daimon del Guerriero e del Trionfo. Rappresenta il processo di incarnazione e manifestazione terrena dello spirito: la discesa della luce invisibile nel sangue rosso e nella carne. È la corazza immaginale che protegge l'Anima nel viaggio.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=600&q=80",
    tags: ["Forza Cinetica", "Sangue di Ferro", "Manifestazione", "Scudo Metallico"],
    chakraName: "Muladhara - Chakra della Radice (Primo Chakra)",
    chakraMotivazione: "Il nucleo rosso sangue di ferro dell'Ematite rappresenta la pura linfa emoglobinica che spinge all'azione, allineandosi a Muladhara per muovere il Carro del trionfo terreno.",
    chakraPuntiForza: "Focus incrollabile, grande resistenza fisica, protezione aurica densa e capacità di direzione risoluta.",
    chakraPuntiDebolezza: "Iperattività aggressiva, impulsività rabbiosa, tendenza a forzare le tappe esaurendo le riserve energetiche.",
    chakraEquilibrio: "Sfregare l'ematite sulle piante dei piedi per scaricare il surplus mentale; eseguire respirazioni profonde con focus sulla spina dorsale."
  },
  {
    number: 8,
    roman: "VIII",
    arcanaName: "La Forza",
    mineralName: "Occhio di Tigre",
    subTitle: "Quarzo Pseudomorfo",
    formula: "SiO₂ + Crocidolite",
    system: "Trigonale (Pseudomorfo)",
    hardness: 7,
    category: "Silicato (Pseudomofosi)",
    colorGradient: "from-amber-600/20 via-yellow-700/10 to-stone-800/5",
    accentColor: "#d97706",
    scientificBasis: "Nasce dalla silicizzazione della crocidolite (amianto azzurro fibroso), le cui fibre rigide e orientate vengono progressivamente sostituite da silice e limonite dorata. Incarna il controllo armonico delle pulsioni istintive.",
    opticsPhysical: "Gatteggiamento (chatoyancy) setoso dorato-marrone dovuto alla perfetta conservazione fibrosa originaria.",
    materiale: "Varietà di quarzo microcristallino contenente fibre orientate di crocidolite (anfibolo) parzialmente alterate in limonite. Presenta durezza 7 e frattura fibrosa. Mostra uno splendido gioco luminoso ondulatorio a riflesso cangiante.",
    spirituale: "Rappresenta l'equilibrio tra l'istinto animale originario e la coscienza superiore. È la trasmutazione del veleno o della debolezza (le fibre d'amianto fragili) in una pietra indistruttibile di puro silicio dorato.",
    immaginale: "Il Daimon della Trasmutazione e del Coraggio. Rappresenta la capacità immaginale di cavalcare l'istinto senza reprimerlo né farsi travolgere, trasmutandolo in una risorsa energetica flessibile e luminosa. È lo sguardo vigile della tigre dell'anima.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=600&q=80",
    tags: ["Trasmutazione", "Gatteggiamento", "Autocontrollo", "Silicizzazione"],
    chakraName: "Manipura - Chakra del Plesso Solare (Terzo Chakra)",
    chakraMotivazione: "La silicizzazione dell'amianto velenoso in un occhio di luce cangiante dorata riflette perfettamente il coraggio della Forza nel trasmutare gli istinti nel forno alchemico del Plesso Solare.",
    chakraPuntiForza: "Padronanza assoluta degli istinti vitali, coraggio morale saldo, magnetismo regale e carisma integrato.",
    chakraPuntiDebolezza: "Orgoglio feroce, repressione distruttiva della propria natura selvatica e sfoghi psicosomatici nel ventre.",
    chakraEquilibrio: "Meditare stringendo l'occhio di tigre sul plesso ed esporsi alla luce calda solare; visualizzare le pulsioni animali come fiamme che riscaldano anziché bruciare."
  },
  {
    number: 9,
    roman: "IX",
    arcanaName: "L'Eremita",
    mineralName: "Ossidiana",
    subTitle: "Vetro Vulcanico Amorfo",
    formula: "SiO₂ (Vetro Amorfo)",
    system: "Amorfo",
    hardness: 5.5,
    category: "Vetro Vulcanico",
    colorGradient: "from-stone-900/40 via-slate-900/30 to-purple-950/10",
    accentColor: "#64748b",
    scientificBasis: "Vetro vulcanico nato dal raffreddamento istantaneo della lava, che non lascia il tempo agli atomi di organizzarsi in un reticolo ordinato. Incarna la concentrazione interna e il silenzioso rigore dell'isolamento.",
    opticsPhysical: "Assenza totale di struttura cristallina a lungo raggio, frattura concoide estremamente affilata.",
    materiale: "Roccia effusiva vetrosa di composizione acida (ricca di silice). Poiché si raffredda istantaneamente all'aria o in acqua, la sua struttura rimane amorfa. Ha durezza 5-5.5 e si rompe generando spigoli vivi di spessore molecolare.",
    spirituale: "Rappresenta l'ascesi silenziosa e la luce interiore nascosta sotto l'apparenza scura. È la discesa consapevole nelle proprie tenebre per trovare la scintilla della Verità, l'isolamento ascetico che distrugge le illusioni superficiali dell'ego.",
    immaginale: "Il Daimon dello Specchio Oscuro e dell'Ombra. Nella psicologia immaginale rappresenta lo specchio nero in cui l'Io affronta la propria ombra primordiale. È le guardiano silenzioso che custodisce il fuoco creativo interiore nel profondo silenzio della terra.",
    crystalShape: "amorphous",
    imageUrl: "https://images.unsplash.com/photo-1614362145802-53b708304959?auto=format&fit=crop&w=600&q=80",
    tags: ["Struttura Amorfa", "Integrità", "Specchio dell'Ombra", "Ritiro"],
    chakraName: "Muladhara - Chakra della Radice (Primo Chakra)",
    chakraMotivazione: "Il vetro vulcanico scuro e tagliente dell'Ossidiana radica l'energia psichica più profonda, aiutando l'Eremita a camminare impavido nel buio della grotta interiore.",
    chakraPuntiForza: "Scudo protettivo eccezionale, integrità interiore, rimozione radicale di nodi karmici e illusioni dell'ego.",
    chakraPuntiDebolezza: "Chiusura fredda all'esterno, tendenza al cinismo, paura del calore umano ed evitamento dei sentimenti.",
    chakraEquilibrio: "Meditare tenendo l'ossidiana alle estremità inferiori del corpo; visualizzare le paure inconsce liquefarsi come lava ed essere assorbite dalla terra."
  },
  {
    number: 10,
    roman: "X",
    arcanaName: "La Ruota della Fortuna",
    mineralName: "Opale",
    subTitle: "Silice Idrata",
    formula: "SiO₂·nH₂O",
    system: "Mineraloide",
    hardness: 6,
    category: "Mineraloide (Silice Idrata)",
    colorGradient: "from-teal-300/20 via-purple-400/10 to-amber-300/5",
    accentColor: "#2dd4bf",
    scientificBasis: "Esibisce l'opalescenza e la giostra cromatica dovuta alla diffrazione della luce che attraversa nanosfere ordinate di silice immerse in acqua interstiziale. Simboleggia il mutamento continuo e la dinamicità ciclica.",
    opticsPhysical: "Iridescenza per interazione ottica su nanosfere (150-300 nm), contenuto d'acqua variabile (fino al 21%).",
    materiale: "Silice amorfa idrata contenente dal 3% al 21% di acqua. Non è un vero minerale ma un mineraloide. Il gioco di colori nasce dalla disposizione ordinata di microscopiche sfere di silice che creano un reticolo di diffrazione naturale per la luce.",
    spirituale: "Rappresenta il mutamento eterno e il fluire perpetuo delle cose. Ricorda che la forma esterna è fluida e impermanente (come l'acqua racchiusa nella pietra), mentre l'essenza spirituale continua a risplendere in infinite combinazioni di colore.",
    immaginale: "Il Daimon del Gioco e delle Metamorfosi. Simboleggia l'immaginazione fluida capace di assumere qualsiasi forma, colore e prospettiva senza irrigidirsi mai. Rappresenta la ruota dei destini psichici che gira continuamente, svelando nuove prospettive dell'essere.",
    crystalShape: "amorphous",
    imageUrl: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=600&q=80",
    tags: ["Opalescenza", "Mutamento Fluido", "Nanosfere", "Metamorfosi"],
    chakraName: "Svadhisthana - Chakra Sacrale (Secondo Chakra)",
    chakraMotivazione: "L'Opale, contenente acqua vitale racchiusa in una struttura silicea iridescente, incarna il movimento incessante e il gioco dei desideri e dei mutamenti del secondo chakra.",
    chakraPuntiForza: "Creatività liquida, spontaneità estatica, capacità di assecondare i flussi della vita senza resistenza.",
    chakraPuntiDebolezza: "Estrema labilità emotiva, dispersione energetica e senso di sradicamento dovuto al continuo movimento del destino.",
    chakraEquilibrio: "Prendere un bagno tiepido rilassante tenendo un opale vicino; praticare danze fluide ed espressive assecondando il proprio ritmo interiore."
  },
  {
    number: 11,
    roman: "XI",
    arcanaName: "La Giustizia",
    mineralName: "Fluorite",
    subTitle: "Fluoruro di Calcio",
    formula: "CaF₂",
    system: "Cubico",
    hardness: 4,
    category: "Alogenuro",
    colorGradient: "from-purple-500/20 via-emerald-600/10 to-blue-500/5",
    accentColor: "#c084fc",
    scientificBasis: "Dotata di una sfaldatura ottaedrica geometricamente perfetta in 4 direzioni. Mostra una forte fluorescenza sotto i raggi UV. Incarna l'equilibrio rigoroso, la trasparenza logica, l'ordine razionale e l'imparzialità.",
    opticsPhysical: "Fluorescenza spiccata per attivazione di impurità di terre rare, sfaldatura ottaedrica geometrica perfetta.",
    materiale: "Fluoruro di calcio (CaF₂). Cristallizza nel sistema cubico, formando spesso geminati di compenetrazione o ottaedri perfetti per sfaldatura. Ha una durezza di 4 e presenta una gamma cromatica vastissima dovuta a difetti strutturali o elementi in traccia.",
    spirituale: "Rappresenta l'equilibrio cosmico del discernimento e della giustizia divina. È la capacità di separare con impeccabile precisione la verità dall'illusione (rappresentata dai perfetti piani di sfaldatura ottaedrica che emergono dal cubo).",
    immaginale: "Il Daimon dell'Equilibrio e della Chiarezza Mentale. Nella psicologia immaginale rappresenta il principio ordinatore che porta armonia e pace nell'anarchia emotiva, cristallizzando i pensieri vaghi in forme simmetriche e comprensibili.",
    crystalShape: "cubic",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=600&q=80",
    tags: ["Sfaldatura Ottaedrica", "Discernimento", "Fluorescenza", "Simmetria"],
    chakraName: "Ajna - Chakra del Terzo Occhio (Sesto Chakra)",
    chakraMotivazione: "La sfaldatura ottaedrica perfetta della Fluorite simboleggia il massimo discernimento della Giustizia, strutturando le nebbie mentali tramite la precisione di Ajna.",
    chakraPuntiForza: "Logica adamantina, discernimento geometrico, stabilità focalizzata e sintonizzazione di onde cerebrali superiori.",
    chakraPuntiDebolezza: "Eccessivo cerebralismo analitico, freddezza critica e incapacità di sintonizzarsi sull'intelligenza del cuore.",
    chakraEquilibrio: "Meditare focalizzando la mente su un ottaedro di fluorite illuminato; posizionarla sulla fronte per ripristinare chiarezza e simmetria cognitiva."
  },
  {
    number: 12,
    roman: "XII",
    arcanaName: "L'Appeso",
    mineralName: "Acquamarina",
    subTitle: "Berillo Azzurro",
    formula: "Be₃Al₂Si₆O₁₈:Fe²⁺",
    system: "Esagonale",
    hardness: 7.8,
    category: "Silicato (Ciclosilicato)",
    colorGradient: "from-cyan-400/20 via-blue-500/10 to-sky-200/5",
    accentColor: "#38bdf8",
    scientificBasis: "Varietà limpida di berillo azzurro, il cui colore pastello è causato da ioni di ferro ferroso Fe²⁺ nel canale strutturale. Simboleggia la resa pacifica, la sospensione attiva, la limpidezza fluida e la percezione ribaltata.",
    opticsPhysical: "Dicroismo trasparente blu/incolore, elevata trasmittanza nell'azzurro, eccezionale limpidezza interna.",
    materiale: "Varietà azzurro-celeste del berillo. Cristallizza nel sistema esagonale in lunghi prismi striati. Durezza eccezionale (7.5-8). Il colore azzurro o verde-azzurro è dovuto alla presenza di ferro bivalente (Fe²⁺) che occupa i canali strutturali.",
    spirituale: "Rappresenta lo stato di profonda pace interiore che deriva dall'arrendersi al flusso cosmico. È la purezza dell'acqua spirituale che purifica la mente, permettendo di guardare il mondo da una prospettiva capovolta senza opporre resistenza.",
    immaginale: "Il Daimon del Flusso e della Rinuncia. Rappresenta l'accettazione consapevole dei cicli di attesa e la saggezza di chi sa che la vera forza risiede nella fluidità e nella non-azione. È la mente limpida come un mare calmo che riflette il cielo.",
    crystalShape: "hexagonal",
    imageUrl: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=600&q=80",
    tags: ["Sospensione Attiva", "Ferro Fe²⁺", "Limpidezza Celeste", "Resa"],
    chakraName: "Vishuddha - Chakra della Gola (Quinto Chakra)",
    chakraMotivazione: "La quiete liquida dell'Acquamarina distende la muscolatura laringea e rilascia il controllo oratorio, aprendo Vishuddha alla totale arresa del proprio sé egoico al Sé Superiore.",
    chakraPuntiForza: "Arresa pacifica consapevole, rilascio dei conflitti, eloquenza dolce e sincerità emotiva.",
    chakraPuntiDebolezza: "Passività vittimistica, tendenza al mutismo difensivo e paura di prendere posizione dinanzi alle ingiustizie.",
    chakraEquilibrio: "Riposare con un'acquamarina sul collo ascoltando il suono naturale dello scorrere delle acque; praticare la recitazione di suoni calmi."
  },
  {
    number: 13,
    roman: "XIII",
    arcanaName: "La Morte",
    mineralName: "Tormalina Nera",
    subTitle: "Schorl",
    formula: "NaFe³⁺₃Al₆(BO₃)₃Si₆O₁₈(OH)₄",
    system: "Trigonale",
    hardness: 7.2,
    category: "Silicato (Borosilicato)",
    colorGradient: "from-slate-900/50 via-zinc-900/40 to-stone-900/30",
    accentColor: "#475569",
    scientificBasis: "Dotata di spiccata piroelettricità e piezoelettricità: se riscaldata o compressa accumula polarità elettriche opposte alle estremità. Incarna il taglio netto, lo scudo protettivo radicale e la trasmutazione.",
    opticsPhysical: "Assorbimento ottico totale nel visibile, conducibilità anisotropa lungo l'asse allungato.",
    materiale: "Borosilicato complesso di sodio e ferro. Cristallizza nel sistema trigonale in prismi allungati e striati longitudinalmente. Ha durezza 7-7.5. È nota per l'assorbimento quasi completo delle radiazioni elettromagnetiche visibili.",
    spirituale: "Rappresenta la fine necessaria e la purificazione radicale. Come la pietra devia e scarica a terra le tensioni elettromagnetiche dannose, così questo archetipo distrugge i legami tossici e le strutture rigide, liberando l'essenza spirituale.",
    immaginale: "Il Daimon del Taglio e della Rigenerazione. Simboleggia il rigore necessario per morire a ciò che è superfluo per rinascere nello spirito. È il guardiano oscuro della soglia alchemica che transmuta l'ombra in energia protettiva.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=600&q=80",
    tags: ["Piroelettrico", "Schermatura Totale", "Morte Iniziatica", "Taglio"],
    chakraName: "Muladhara - Chakra della Radice (Primo Chakra)",
    chakraMotivazione: "La Tormalina Nera, grazie alle sue eccezionali proprietà piroelettriche e di assorbimento delle densità cariche, àncora a terra e purifica l'energia primordiale di Muladhara durante la crisi trasformativa della Morte.",
    chakraPuntiForza: "Schermatura totale contro le tossicità, forza interiore rigenerativa e distacco alchemico netto da ciò che è morto.",
    chakraPuntiDebolezza: "Terrore radicato della perdita biologica, ostinato attaccamento difensivo e blocco dell'istinto di sopravvivenza.",
    chakraEquilibrio: "Tenere una tormalina nera sul coccige visualizzando flussi grigio-scuri nocivi che scaricano nel nucleo della terra fertile."
  },
  {
    number: 14,
    roman: "XIV",
    arcanaName: "La Temperanza",
    mineralName: "Ametista",
    subTitle: "Quarzo Viola",
    formula: "SiO₂ + Fe³⁺ / Irradiazione",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato",
    colorGradient: "from-purple-600/20 via-violet-800/10 to-indigo-500/5",
    accentColor: "#a855f7",
    scientificBasis: "Varietà di quarzo la cui sfumatura viola nasce da tracce di ferro trivalente Fe³⁺ sottoposte a irradiazione gamma naturale delle rocce. Rappresenta l'equilibrio alchemico degli opposti e la fluidità temperata.",
    opticsPhysical: "Pleocroismo violetto evidente, scolorimento se sottoposta a forte calore (diviene citrino).",
    materiale: "Biossido di silicio contenente atomi di ferro trivalente sostitutivi nel reticolo della silice. L'esposizione prolungata a radiazioni naturali ionizzanti genera 'centri di colore' stabili che assorbono la luce verde-gialla, donando il viola.",
    spirituale: "Rappresenta la trasmutazione spirituale, la purificazione delle passioni e l'unione armoniosa degli opposti (il rosso del fuoco passionale e il blu della calma celestiale fusi nel viola). È il custode del giusto mezzo e della misura sacra.",
    immaginale: "Il Daimon del Calice Alchemico e della Misura. È l'archetipo che pacifica le tensioni interiori, insegnando all'Anima a scorrere come acqua pura tra gli estremi dell'esistenza senza mai rompersi. Rappresenta la guarigione immaginale attraverso la sintesi.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?auto=format&fit=crop&w=600&q=80",
    tags: ["Alchimia", "Centri di Colore", "Giusto Mezzo", "Trasmutazione"],
    chakraName: "Ajna / Sahasrara - Sesto e Settimo Chakra (Terzo Occhio e Corona)",
    chakraMotivazione: "La fusione ottica del rosso passivo e del blu astratto nell'Ametista viola incarna lo stato temperato e curativo di chi armonizza le passioni terrene, sintonizzando la mente verso stati di coscienza superiori.",
    chakraPuntiForza: "Grande equilibrio psicofisico, diplomazia empatica innata e forte percezione intuitiva del sacro quotidiano.",
    chakraPuntiDebolezza: "Disincarnazione ascetica, rifiuto dei bisogni del corpo fisico e fuga idealistica dalle fatiche materiali.",
    chakraEquilibrio: "Sedersi in meditazione stringendo una punta di ametista orientata verso l'alto; visualizzare una fiamma violetta purificante attorno all'aura."
  },
  {
    number: 15,
    roman: "XV",
    arcanaName: "Il Diavolo",
    mineralName: "Magnetite",
    subTitle: "Ossido di Ferro Magnetico",
    formula: "Fe₃O₄",
    system: "Cubico",
    hardness: 6,
    category: "Ossido",
    colorGradient: "from-zinc-800/30 via-neutral-900/20 to-amber-900/5",
    accentColor: "#71717a",
    scientificBasis: "Il minerale naturalmente più magnetico sulla Terra (ferrimagnetismo naturale permanente). Incarna la forza di gravità incontrollabile, i vincoli materiali duraturi, l'attrazione viscerale e le legame fisico.",
    opticsPhysical: "Ferrimagnetismo permanente dovuto allo sbilanciamento di spin tra gli ioni Fe²⁺ e Fe³⁺ nei siti strutturali.",
    materiale: "Ossido misto di ferro bivalente e trivalente. Cristallizza nel sistema cubico in splendidi ottaedri neri opachi. Durezza 5.5-6.5. Ha un forte magnetismo naturale in grado di attrarre la limatura di ferro e deviare gli aghi delle bussole.",
    spirituale: "Rappresenta l'incarnazione più densa della materia, le catene dorate dell'attrazione magnetica terrestre e l'energia sessuale/creativa originaria non canalizzata. È la trappola del materialismo ma anche la chiave per padroneggiare le correnti telluriche.",
    immaginale: "Il Daimon del Legame Magnetico e del Desiderio. Nella psicologia immaginale rappresenta le passioni viscerali che incatenano l'anima alla terra, ma che costituiscono anche la materia prima indispensabile per l'Opera. È l'attrazione fatale delle immagini.",
    crystalShape: "cubic",
    imageUrl: "https://images.unsplash.com/photo-1614362145802-53b708304959?auto=format&fit=crop&w=600&q=80",
    tags: ["Ferrimagnetismo", "Catene della Materia", "Ottoredo Nero", "Passione"],
    chakraName: "Muladhara - Chakra della Radice (Primo Chakra)",
    chakraMotivazione: "Il ferrimagnetismo permanente della Magnetite simboleggia l'intensa attrazione magnetica gravitazionale della materia e degli istinti densi dominati dal Diavolo, legandoli visceralmente a Muladhara.",
    chakraPuntiForza: "Irresistibile attrazione e carisma personale, immensa vitalità fisica e perfetto radicamento nell'abbondanza materiale.",
    chakraPuntiDebolezza: "Attaccamento morboso tossico, brama ossessiva di controllo egoico, dipendenze fisiche ed avidità spirituale.",
    chakraEquilibrio: "Praticare movimenti lenti del bacino e di rilascio miofasciale massaggiando i punti contratti con magnetite; visualizzare le linee di flusso magnetico equilibrarsi nell'asse corporeo."
  },
  {
    number: 16,
    roman: "XVI",
    arcanaName: "La Torre",
    mineralName: "Fulgurite",
    subTitle: "Vetro Silicico d'Impatto",
    formula: "SiO₂ (Vetro da Fulmine)",
    system: "Amorfo d'Impatto",
    hardness: 6,
    category: "Vetro d'Impatto",
    colorGradient: "from-amber-300/20 via-red-500/10 to-slate-900/5",
    accentColor: "#f59e0b",
    scientificBasis: "Si forma all'istante quando un fulmine colpisce il suolo sabbioso, fondendone istantaneamente la silice a temperature superiori ai 1800°C. Rappresenta lo shock distruttivo improvviso e l'energia folgorante.",
    opticsPhysical: "Struttura tubolare cava amorfa rugosa all'esterno e vetrosa levigata all'interno.",
    materiale: "Vetro naturale silico-alluminoso amorfo formatosi dall'impatto di un fulmine su sabbie quarzose o rocce silicatiche. Si presenta come tubi rugosi, ramificati e cavi internamente, dovuti all'espansione rapida del vapore acqueo.",
    spirituale: "Rappresenta la folgore divina che distrugge la torre dell'orgoglio o le false certezze dell'Io. È l'intervento improvviso dello Spirito che spezza i vecchi schemi cristallizzati per costringere l'essere a ricominciare su basi autentiche.",
    immaginale: "Il Daimon della Folgore e del Crollo. Nella psicologia immaginale è l'archetipo della crisi liberatoria: la distruzione delle corazze difensive che imprigionavano l'Anima. È l'istante cosmico in cui il cielo bacia la terra col fuoco.",
    crystalShape: "amorphous",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    tags: ["Folgore", "Crollo Liberatorio", "Shock Termico", "Tubo di Silice"],
    chakraName: "Manipura - Chakra del Plesso Solare (Terzo Chakra)",
    chakraMotivazione: "La fulminea scarica elettrica termica che crea la Fulgurite rispecchia la demolizione violenta e improvvisa delle corazze dell'ego, catalizzando una liberazione bruciante nel plesso solare.",
    chakraPuntiForza: "Rottura immediata di catene psichiche logore, purificazione traumatica ma catartica e rivelazione istantanea della verità.",
    chakraPuntiDebolezza: "Shock post-traumatico, spossatezza estrema del sistema nervoso e strenua resistenza cosciente al cambiamento.",
    chakraEquilibrio: "Praticare respirazioni respiratorie catartiche (Breathwork) stringendo delicatamente la fulgurite sul plesso solare; lasciare andare le tensioni viscerali con suoni liberatori."
  },
  {
    number: 17,
    roman: "XVII",
    arcanaName: "La Stella",
    mineralName: "Zaffiro Stellato",
    subTitle: "Corindone con Asterismo",
    formula: "Al₂O₃:Ti",
    system: "Trigonale",
    hardness: 9,
    category: "Ossido (Corindone)",
    colorGradient: "from-blue-500/20 via-cyan-600/10 to-indigo-300/5",
    accentColor: "#60a5fa",
    scientificBasis: "Corindone blu che presenta l'asterismo: una stella luminosa a 6 punte dovuta alla riflessione della luce su microscopici aghi orientati di rutilo. Rappresenta la speranza, la fede e la guida celeste.",
    opticsPhysical: "Asterismo ottico perfect visibile in luce puntiforme diretta, durezza record (seconda solo al diamante).",
    materiale: "Ossido di alluminio puro (corindone). Cristallizza nel sistema trigonale. Durezza eccezionale (9 Mohs). Il colore blu è dovuto a tracce di ferro e titanio; la presenza di aghi microscopici di rutilo orientati a 120° genera il fenomeno ottico dell'asterismo.",
    spirituale: "Rappresenta la guida interiore, la fede incrollabile nel destino spirituale e la luce che brilla nelle tenebre dell'inconscio. È la stella polare dell'Anima che indica la via del ritorno all'Unità cosmica attraverso la speranza attiva.",
    immaginale: "Il Daimon dell'Asterismo e della Visione Stellare. Simboleggia la capacità immaginale di scorgere un ordine poetico e luminoso (la stella) anche nella materia più densa o nelle notti più buie della psiche. È la poesia cosmica curativa.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=600&q=80",
    tags: ["Asterismo", "Speranza Cosmica", "Durezza 9", "Aghi di Rutilo"],
    chakraName: "Ajna - Chakra del Terzo Occhio (Sesto Chakra)",
    chakraMotivazione: "La stella simmetrica a sei punte che brilla sul velluto azzurro dello Zaffiro evoca il Terzo Occhio che scorge la mappa sacra dell'Anima Mundi, donando fede nel cammino stellare.",
    chakraPuntiForza: "Fede profonda nel destino cosmico, visione profetica, ottimismo poetico e chiarezza di percorso.",
    chakraPuntiDebolezza: "Evitamento della realtà terrena, astrazione sterile, fantasticherie eccessive e distacco emotivo algido.",
    chakraEquilibrio: "Sdraiarsi sotto il cielo stellato adagiando lo zaffiro stellato sulla fronte; visualizzare la stella a sei punte interiore che illumina la via."
  },
  {
    number: 18,
    roman: "XVIII",
    arcanaName: "La Luna",
    mineralName: "Selenite",
    subTitle: "Gesso Satinato",
    formula: "CaSO₄·2H₂O",
    system: "Monoclinico",
    hardness: 2,
    category: "Solfato",
    colorGradient: "from-slate-200/20 via-indigo-100/10 to-sky-300/5",
    accentColor: "#e2e8f0",
    scientificBasis: "Varietà di gesso fibroso e lucente, formatasi per evaporazione di antichi bacini salini. Estremamente morbida (durezza 2), conduce e diffonde la luce con un bagliore lattiginoso tipico.",
    opticsPhysical: "Bassissima durezza Mohs, trasparenza perlacea-satinata con eccezionale diffusione ottica.",
    materiale: "Solfato di calcio biidrato. Cristallizza nel sistema monoclinico in lamine traslucide o masse fibrose satinatissime. Morbidezza estrema (2 Mohs, si scalfisce con l'unghia). Tipico minerale sedimentario di origine evaporitica.",
    spirituale: "Rappresenta la recettività pura, il mondo dei sogni, dell'inconscio e delle ombre. La sua estrema delicatezza ricorda che la psiche profonda deve essere trattata con immenso rispetto e cura, evitando le rigidità razionali dogmatiche.",
    immaginale: "Il Daimon del Sogno e dello Specchio d'Acqua. Nella psicologia immaginale rappresenta il regno lunare del notturno, dell'immaginazione poetica e delle visioni ancestrali. È la luce soffusa che illumina le profondità marine dell'Anima Mundi.",
    crystalShape: "monoclinic",
    imageUrl: "https://images.unsplash.com/photo-1551269901-5c5e14c25df7?auto=format&fit=crop&w=600&q=80",
    tags: ["Luce Lattiginoso", "Regno del Sogno", "Evaporite", "Morbidezza"],
    chakraName: "Sahasrara - Chakra della Corona (Settimo Chakra)",
    chakraMotivazione: "L'irradiazione lattiginosa e impalpabile della Selenite, con la sua eccezionale morbidezza strutturale evaporitica, facilita l'apertura ricettiva della corona al regno dell'inconscio e dei sogni.",
    chakraPuntiForza: "Straordinaria sensibilità immaginifica, capacità di accogliere le ombre ancestrali e quiete meditativa profonda.",
    chakraPuntiDebolezza: "Invasione da parte di incubi o illusioni deformanti, estrema vulnerabilità alle emozioni altrui e debolezza dei confini dell'Io.",
    chakraEquilibrio: "Mettere un blocco di selenite vicino alla testiera del letto per propiziare sonno quieto e sogni lucidi; meditare visualizzando una doccia di luce argentea perlacea."
  },
  {
    number: 19,
    roman: "XIX",
    arcanaName: "Il Sole",
    mineralName: "Quarzo Citrino",
    subTitle: "Quarzo Dorato",
    formula: "SiO₂ + Fe³⁺",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato",
    colorGradient: "from-amber-400/20 via-yellow-500/10 to-orange-400/5",
    accentColor: "#fbbf24",
    scientificBasis: "Quarzo cromatico dorato, la cui splendida lucentezza solare è dovuta a tracce di ferro trivalente in sostituzione tetraedrica. Incarna la massima chiarezza e radianza.",
    opticsPhysical: "Elevata trasmittanza ottica nel giallo-arancione, assenza di sfaldatura, lucentezza vitrea intensa e stabile.",
    materiale: "Biossido di silicio contenente atomi sostitutivi di ferro trivalente in una configurazione di risonanza molecolare che assorbe la luce violetta. Durezza 7. Molto raro in natura in campioni non riscaldati artificialmente.",
    spirituale: "Rappresenta la Coscienza solare, la gioia di vivere radiosa, la chiarezza dell'intelletto superiore e la fecondità spirituale. È la verità rivelata a mezzogiorno, che scioglie tutte le ombre e riscalda i cuori con la sua generosità cosmica.",
    immaginale: "Il Daimon della Chiarezza e della Radianza. È l'archetipo dell'Io integrato che risplende di luce propria senza accecare, offrendo calore, verità e abbondanza creativa. Simboleggia il Sole dell'Anima pienamente risvegliato.",
    crystalShape: "trigonal",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    tags: ["Radianza Solare", "Trasmittanza Gialla", "Coscienza Sveglia", "Chiarezza"],
    chakraName: "Manipura - Chakra del Plesso Solare (Terzo Chakra)",
    chakraMotivazione: "La trasmittanza gialla dorata splendente del Quarzo Citrino incarna la vitalità calda e pura del Sole, irradiando ed eliminando ogni ristagno energetico nel Plesso Solare.",
    chakraPuntiForza: "Ottimismo contagioso, vitalità maestosa, autostima solida e coraggioso senso di generosità.",
    chakraPuntiDebolezza: "Iperattivismo bruciante, egocentrismo accecante e intolleranza verso le zone d'ombra personali o collettive.",
    chakraEquilibrio: "Esporsi alla luce solare del primo mattino cullando il citrino sul plesso solare; praticare respirazioni ritmiche colme di sentimenti di gratitudine attiva."
  },
  {
    number: 20,
    roman: "XX",
    arcanaName: "Il Giudizio",
    mineralName: "Moldavite",
    subTitle: "Tettite d'Impatto Cosmogenerato",
    formula: "Vetro d'Impatto Cosmetico",
    system: "Amorfo d'Impatto",
    hardness: 5.5,
    category: "Tettite",
    colorGradient: "from-emerald-700/20 via-lime-900/10 to-teal-950/5",
    accentColor: "#4ade80",
    scientificBasis: "Nata 15 milioni di anni fa dalla fusione istantanea e dal lancio ad alta quota di rocce terrestri colpite da un meteorite. Simboleggia la chiamata dall'alto e la trasmutazione cosmica.",
    opticsPhysical: "Superficie scolpita dall'attrito aerodinamico di rientro, fluidità vetrosa verde-oliva con bolle microscopiche.",
    materiale: "Vetro siliceo naturale (tettite) formatosi dall'impatto di un gigantesco meteorite nella Germania meridionale. Durezza 5.5. Presenta una splendida tonalità verde foresta traslucida con scanalature aerodinamiche sulla superficie.",
    spirituale: "Rappresenta il Risveglio spirituale, la chiamata a trascendere i limiti terrestri per aprirsi alla dimensione cosmica. È l'alleanza sigillata col fuoco tra il Cielo (il meteorite) e la Terra (le rocce fuse), la resurrezione alchemica dell'essere.",
    immaginale: "Il Daimon del Risveglio Cosmico. Simboleggia lo shock evolutivo che scuote l'Anima dal suo sonno terrestre millenario, ricordandole la sua vera origine stellare. È l'archetipo del salto quantico psichico, la metamorfosi verde.",
    crystalShape: "amorphous",
    imageUrl: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?auto=format&fit=crop&w=600&q=80",
    tags: ["Origine Meteoritica", "Risveglio Iniziatico", "Tettite Verde", "Salto Quantico"],
    chakraName: "Anahata / Ajna - Quarto e Sesto Chakra (Cuore e Terzo Occhio)",
    chakraMotivazione: "Essendo una rarissima tettite d'impatto meteoritico verde oliva traslucida, fonde l'elemento celeste (il meteorite) con quello terreno, destando il Cuore (Anahata verde) e sintonizzando il Terzo Occhio al risveglio del Giudizio.",
    chakraPuntiForza: "Risveglio psichico di eccezionale rapidità, apertura cosmica e comprensione istantanea delle grandi trame del destino.",
    chakraPuntiDebolezza: "Mancanza di acclimatamento terreno (vivere 'fuori dal mondo'), shock energetico e vertigini psichiche repentine.",
    chakraEquilibrio: "Alternare la moldavite sul cuore a pietre di radicamento (ematite, ossidiana) per non sradicare la psiche dal corpo; respirare a fondo con la terra."
  },
  {
    number: 21,
    roman: "XXI",
    arcanaName: "Il Mondo",
    mineralName: "Diamante",
    subTitle: "Carbonio Puro Covalente",
    formula: "C",
    system: "Cubico",
    hardness: 10,
    category: "Elemento Nativo",
    colorGradient: "from-cyan-200/20 via-blue-300/10 to-purple-200/5",
    accentColor: "#38bdf8",
    scientificBasis: "La sostanza naturale più dura sulla Terra, formata da un reticolo tridimensionale perfetto di carbonio con legami covalenti equivalenti. Simboleggia l'integrità totale e il compimento perfetto del ciclo.",
    opticsPhysical: "Durezza 10 Mohs assoluta, elevatissimo indice di rifrazione (2.42), conducibilità termica eccezionale.",
    materiale: "Carbonio elementare puro cristallizzato nel sistema cubico a pressioni estreme del mantello terrestre. Ha durezza massima 10 sulla scala Mohs, sfaldatura ottaedrica perfetta e una dispersione ottica straordinaria (fuoco del diamante).",
    spirituale: "Rappresenta la realizzazione spirituale suprema, l'integrità incorruttibile, il Sé unificato e l'illuminazione totale. È l'oro filosofale dei saggi, la coscienza atomica pura che ha superato ogni prova e brilla di gloria eterna.",
    immaginale: "Il Daimon della Perfezione e del Compimento. Nella psicologia immaginale rappresenta l'individuazione compiuta (Jung), lo stato in cui tutte le parti frammentate della psiche sono state integrate in un reticolo di diamante eterno, indistruttibile e luminoso.",
    crystalShape: "cubic",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80",
    tags: ["Incorruttibile", "Individuazione", "Carbonio Covalente", "Compimento"],
    chakraName: "Tutti i 7 Chakra Allineati (Integrazione Suprema)",
    chakraMotivazione: "Il Diamante, carbonio covalente indistruttibile con indice di rifrazione assoluto, simboleggia il compimento dell'Opera del Mondo, allineando e unificando tutti i 7 chakra in una pura colonna di luce adamantina.",
    chakraPuntiForza: "Incorruttibilità assoluta alle alterazioni esterne, autorealizzazione del Sé e radiosa integrità morale.",
    chakraPuntiDebolezza: "Distacco e gelido isolamento dal calore ordinario dei sentimenti umani terreni.",
    chakraEquilibrio: "Meditare visualizzando una cascata di luce adamantina che scende dall'universo ed attraversa ciascuno dei sette chakra, purificando ed unificando l'asse centrale dell'essere."
  }
];
