import { ArcanoMineral } from './types';

export const ARCANA_DATA: ArcanoMineral[] = [
  {
    number: 0,
    roman: "0",
    arcanaName: "Il Matto",
    mineralName: "Quarzo Ialino",
    subTitle: "Cristallo di Rocca",
    formula: "SiO₂",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato",
    colorGradient: "from-slate-200/20 via-sky-100/10 to-blue-200/5",
    accentColor: "#e0f2fe",
    scientificBasis: "Trasparente e privo di impurità cromatiche, contiene in potenza l'intero spettro della luce visibile. Incarna la tabula rasa, il potenziale puro, lo stato di energia originaria e non polarizzata.",
    opticsPhysical: "Trasparenza ottica completa, piezoelettricità elevata, rifrazione limpida.",
    tags: ["Potenziale Puro", "Trasparenza", "Inizio", "Piezoelettrico"]
  },
  {
    number: 1,
    roman: "I",
    arcanaName: "Il Bagatto",
    mineralName: "Pirite",
    subTitle: "Solfuro di Ferro",
    formula: "FeS₂",
    system: "Cubico",
    hardness: 6.5,
    category: "Solfuro",
    colorGradient: "from-amber-400/20 via-yellow-600/10 to-amber-200/5",
    accentColor: "#f59e0b",
    scientificBasis: "Solfuro di ferro dai riflessi metallici dorati con perfetti cristalli cubici o pentagonododecaedrici. Rappresenta la materia grezza organizzata con millimetrica precisione e la scintilla originaria (se percossa genera faville).",
    opticsPhysical: "Lucentezza metallica, sfaldatura imperfetta, genesi idrotermale/sedimentaria.",
    tags: ["Geometria Cubica", "Scintilla", "Organizzazione", "Metallo"]
  },
  {
    number: 2,
    roman: "II",
    arcanaName: "La Papessa",
    mineralName: "Pietra di Luna",
    subTitle: "Adularia",
    formula: "KAlSi₃O₅",
    system: "Monoclinico",
    hardness: 6,
    category: "Feldspato",
    colorGradient: "from-indigo-300/20 via-slate-400/10 to-purple-300/5",
    accentColor: "#c084fc",
    scientificBasis: "Esibisce il fenomeno ottico dell'adularescenza: un bagliore azzurro-biancastro fluttuante causato dalla diffusione della luce tra strati microscopici alternati di albite ed ortoclasio. Simboleggia la conoscenza velata e il mistero sotto la superficie.",
    opticsPhysical: "Adularescenza (effetto Tyndall/diffrazione), sfaldatura perfetta in 2 direzioni.",
    tags: ["Adularescenza", "Conoscenza Velata", "Feldspato", "Rifrazione"]
  },
  {
    number: 3,
    roman: "III",
    arcanaName: "L'Imperatrice",
    mineralName: "Smeraldo",
    subTitle: "Berillo Verde",
    formula: "Be₃Al₂Si₆O₁₈:Cr",
    system: "Esagonale",
    hardness: 7.8,
    category: "Ciclosilicato",
    colorGradient: "from-emerald-500/20 via-green-600/10 to-teal-400/5",
    accentColor: "#10b981",
    scientificBasis: "Ciclosilicato di berillio ed alluminio arricchito di tracce di cromo e vanadio che generano il caratteristico verde intenso. Rappresenta la forza generatrice della biosfera, la fertilità organica e la vita nel suo massimo splendore.",
    opticsPhysical: "Plecrioismo evidente (verde-blu/verde-giallo), presenza di giardini/inclusione interne.",
    tags: ["Fertilità", "Cromo", "Ciclosilicato", "Vita Organica"]
  },
  {
    number: 4,
    roman: "IV",
    arcanaName: "L'Imperatore",
    mineralName: "Diaspro Rosso",
    subTitle: "Quarzo Microcristallino",
    formula: "SiO₂ + Fe₂O₃",
    system: "Microcristallino",
    hardness: 7,
    category: "Ossido/Silicato",
    colorGradient: "from-red-600/20 via-rose-800/10 to-orange-500/5",
    accentColor: "#ef4444",
    scientificBasis: "Quarzo microcristallino compatto, denso e opaco, ricchissimo di inclusioni di ossidi di ferro (ematite). Presenta elevata compattezza e una stabilità strutturale che incarna la solidità, l'autorità, il rigore e il radicamento.",
    opticsPhysical: "Frattura concoide, densità elevata, opacità ottica totale per micro-inclusioni di Fe.",
    tags: ["Solidità", "Ossido di Ferro", "Autorità", "Compattezza"]
  },
  {
    number: 5,
    roman: "V",
    arcanaName: "Il Papa",
    mineralName: "Lapis Lazzuli",
    subTitle: "Roccia a Lazurite",
    formula: "Roccia (Lazurite + Calcite + Pirite)",
    system: "Roccia Metamorfica",
    hardness: 5.5,
    category: "Roccia Composita",
    colorGradient: "from-blue-600/20 via-indigo-900/10 to-yellow-500/5",
    accentColor: "#3b82f6",
    scientificBasis: "Roccia metamorfica composita costituita da lazurite (blu), calcite (venature bianche) e pirite (pagliuzze dorate). Utilizzato fin dall'antichità per il pigmento sacro blu oltremare, simboleggia l'unione organica di elementi diversi sotto una dottrina o legge comune.",
    opticsPhysical: "Composizione aggregata, presenza di solfuri e silicati congiunti.",
    tags: ["Dottrina", "Composito", "Pigmento Sacro", "Unione"]
  },
  {
    number: 6,
    roman: "VI",
    arcanaName: "Gli Amanti",
    mineralName: "Quarzo Rosa",
    subTitle: "Varietà di Quarzo",
    formula: "SiO₂ + Ti/Mn",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato",
    colorGradient: "from-rose-400/20 via-pink-600/10 to-red-300/5",
    accentColor: "#f472b6",
    scientificBasis: "Deve la sua delicata tonalità rosa a microscopiche inclusioni dicroiche di dumortierite o fibre di titanio/manganese. Incarna la tensione di attrazione molecolare, l'armonia polare tra elementi e la complementarietà chimica.",
    opticsPhysical: "A volte mostra asterismo a 6 punte in sezione sferica, trasparenza traslucida.",
    tags: ["Attrazione", "Complementarietà", "Inclusioni", "Sintesi"]
  },
  {
    number: 7,
    roman: "VII",
    arcanaName: "Il Carro",
    mineralName: "Ematite",
    subTitle: "Ossido di Ferro",
    formula: "Fe₂O₃",
    system: "Trigonale",
    hardness: 6,
    category: "Ossido",
    colorGradient: "from-slate-400/20 via-zinc-700/10 to-red-900/5",
    accentColor: "#94a3b8",
    scientificBasis: "Principale minerale del ferro, pesante e dalla lucentezza metallica speculare grigio-acciaio, ma con polvere e striscia rosso-sangue. Rappresenta la forza propulsiva, la spinta meccanica industriale, l'armatura e la schermatura.",
    opticsPhysical: "Elevatissimo peso specifico (5.26 g/cm³), opacità metallica, striscia rosso marrone.",
    tags: ["Spinta Meccanica", "Metallo Pesante", "Schermatura", "Forza"]
  },
  {
    number: 8,
    roman: "VIII",
    arcanaName: "La Forza",
    mineralName: "Occhio di Tigre",
    subTitle: "Quarzo Pseudomorfo",
    formula: "SiO₂ + Crocidolite",
    system: "Pseudomorfo",
    hardness: 7,
    category: "Silicato",
    colorGradient: "from-amber-600/20 via-yellow-700/10 to-stone-800/5",
    accentColor: "#d97706",
    scientificBasis: "Nasce dalla silicizzazione e pseudomorfosi dell'amianto/crocidolite (fibroso e morbido) sostituito da silicio rigido. Rappresenta il completo dominio della materia, la trasformazione e la disciplina della forza grezza in struttura indistruttibile.",
    opticsPhysical: "Gatteggiamento (chatoyancy) setoso dovuto all'orientamento parallelo delle microscopiche fibre sostituite.",
    tags: ["Gatteggiamento", "Dominio Materia", "Pseudomorfosi", "Forza"]
  },
  {
    number: 9,
    roman: "IX",
    arcanaName: "L'Eremita",
    mineralName: "Ossidiana",
    subTitle: "Vetro Vulcanico Amorfo",
    formula: "SiO₂ (Vetro Amorfo)",
    system: "Amorfo",
    hardness: 5.5,
    category: "Vetro Vulcanico",
    colorGradient: "from-stone-900/40 via-slate-900/30 to-purple-950/10",
    accentColor: "#64748b",
    scientificBasis: "Deriva dal raffreddamento ultra-rapido della lava che impedisce la cristallizzazione: è priva di reticolo cristallino (struttura amorfa). Incarna la concentrazione interna, l'assenza di dispersione, il rigore dell'isolamento e l'introspezione pura.",
    opticsPhysical: "Frattura concoide estremamente tagliente a livello molecolare, vetro naturale privo di ordine a lungo raggio.",
    tags: ["Struttura Amorfa", "Introspezione", "Isolamento", "Frattura Tagliente"]
  },
  {
    number: 10,
    roman: "X",
    arcanaName: "La Ruota della Fortuna",
    mineralName: "Opale",
    subTitle: "Silice Idrata",
    formula: "SiO₂·nH₂O",
    system: "Mineraloide",
    hardness: 6,
    category: "Mineraloide",
    colorGradient: "from-teal-300/20 via-purple-400/10 to-amber-300/5",
    accentColor: "#2dd4bf",
    scientificBasis: "Mostra il fenomeno della giostra cromatica (gioco di colore) causato dalla diffrazione della luce che attraversa una matrice ordinata di nanosfere di silice e acqua intersitiziale. Simboleggia il mutamento continuo, la dinamicità ciclica e l'imprevedibilità.",
    opticsPhysical: "Iridescenza per interazione con nanosfere (150-300 nm), contenuto d'acqua variabile (3-21%).",
    tags: ["Iridescenza", "Mutamento", "Nanosfere", "Dinamismo"]
  },
  {
    number: 11,
    roman: "XI",
    arcanaName: "La Giustizia",
    mineralName: "Fluorite",
    subTitle: "Fluoruro di Calcio",
    formula: "CaF₂",
    system: "Cubico",
    hardness: 4,
    category: "Alogeno",
    colorGradient: "from-purple-500/20 via-emerald-600/10 to-blue-500/5",
    accentColor: "#c084fc",
    scientificBasis: "Caratterizzata da una sfaldatura ottaedrica perfetta in 4 direzioni e da un'impeccabile simmetria nel sistema cubico. È il minerale da cui prende nome il fenomeno della fluorescenza. Rappresenta l'equilibrio geometrico, la chiarezza e l'imparzialità.",
    opticsPhysical: "Sfaldatura ottaedrica immacolata, termoluminescenza e fluorescenza UV spiccata.",
    tags: ["Sfaldatura Perfetta", "Fluorescenza", "Equilibrio", "Simmetria"]
  },
  {
    number: 12,
    roman: "XII",
    arcanaName: "L'Appeso",
    mineralName: "Acquamarina",
    subTitle: "Berillo Azzurro",
    formula: "Be₃Al₂Si₆O₁₈:Fe²⁺",
    system: "Esagonale",
    hardness: 7.8,
    category: "Ciclosilicato",
    colorGradient: "from-cyan-400/20 via-blue-500/10 to-sky-200/5",
    accentColor: "#38bdf8",
    scientificBasis: "Varietà limpida di berillio legata all'elemento fluido. La trasparenza cristallina e il colore derivato dallo stato di ossidazione Fe²⁺ (ferro ferroso) simboleggiano la sospensione, la resa ottica, la ricettività e la limpidezza interiore.",
    opticsPhysical: "Dicroismo trasparente, limpidezza cristallina elevata, resistenza chimica agli acidi.",
    tags: ["Stato Fe²⁺", "Sospensione", "Trasparenza", "Ciclosilicato"]
  },
  {
    number: 13,
    roman: "XIII",
    arcanaName: "La Morte",
    mineralName: "Tormalina Nera",
    subTitle: "Schorl",
    formula: "NaFe³⁺₃Al₆(BO₃)₃Si₆O₁₈(OH)₄",
    system: "Trigonale",
    hardness: 7.2,
    category: "Borosilicato",
    colorGradient: "from-slate-900/50 via-zinc-900/40 to-stone-900/30",
    accentColor: "#475569",
    scientificBasis: "Dotata di straordinarie proprietà piezoelettriche e piroelettriche: se compressa o scaldata accumula cariche elettriche opposte alle estremità. Incarna il taglio netto, la schermatura totale, la rigenerazione energetica e la trasmutazione della materia.",
    opticsPhysical: "Piroelettricità, piezoelettricità, assorbimento completo delle radiazioni elettromagnetiche visibili.",
    tags: ["Piezoelettrico", "Piroelettrico", "Trasmutazione", "Schermatura"]
  },
  {
    number: 14,
    roman: "XIV",
    arcanaName: "La Temperanza",
    mineralName: "Ametista",
    subTitle: "Quarzo Viola",
    formula: "SiO₂ + Fe³⁺ / Irradiazione",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato",
    colorGradient: "from-purple-600/20 via-violet-800/10 to-indigo-500/5",
    accentColor: "#a855f7",
    scientificBasis: "Quarzo la cui sfumatura viola nasce dall'interazione tra tracce di ferro trivalente (Fe³⁺) e il campo di irradiazione gamma naturale delle rocce ospiti. Rappresenta la sintesi alchemica tra il rosso (calore) e il blu (freddo), la misura e l'equilibrio.",
    opticsPhysical: "Plecrioismo violetto/rosso-violetto, stabilità termica con cambio di colore a caldo.",
    tags: ["Centri di Colore", "Alchimia", "Equilibrio Cromatico", "Irradiazione"]
  },
  {
    number: 15,
    roman: "XV",
    arcanaName: "Il Diavolo",
    mineralName: "Magnetite",
    subTitle: "Ossido di Ferro Magnetico",
    formula: "Fe₃O₄",
    system: "Cubico (Spinello)",
    hardness: 6,
    category: "Ossido",
    colorGradient: "from-zinc-800/30 via-neutral-900/20 to-amber-900/5",
    accentColor: "#71717a",
    scientificBasis: "Il minerale naturalmente più magnetico sulla Terra (ferrimagnetismo naturale). Incarna la forza di gravità incontrollabile, i vincoli materiali tangibili, l'attrazione viscerale e la polarità fisica insuperabile.",
    opticsPhysical: "Ferrimagnetismo permanente a temperatura ambiente, devia gli aghi della bussola.",
    tags: ["Ferrimagnetismo", "Attrazione", "Vincolo Materia", "Forza Fisico-Pura"]
  },
  {
    number: 16,
    roman: "XVI",
    arcanaName: "La Torre",
    mineralName: "Fulgurite",
    subTitle: "Vetro Silicico d'Impatto",
    formula: "SiO₂ (Vetro da Fulmine)",
    system: "Amorfo d'Impatto",
    hardness: 6,
    category: "Vetro d'Impatto",
    colorGradient: "from-amber-300/20 via-red-500/10 to-slate-900/5",
    accentColor: "#f59e0b",
    scientificBasis: "Si forma istantaneamente quando un fulmine (fino a 30.000 °C) scarica sulla sabbia fondendo la silice in un tubo vetroso cavo. Rappresenta l'evento improvviso imprevedibile, la rottura strutturale immediata e l'energia istantanea dall'alto.",
    opticsPhysical: "Struttura tubolare cava con pareti interne vetrose lucide ed esterne sabbiose.",
    tags: ["Scarica Elettrica", "Rottura Improvvisa", "Vetro d'Impatto", "Shock Termico"]
  },
  {
    number: 17,
    roman: "XVII",
    arcanaName: "La Stella",
    mineralName: "Zaffiro Stellato",
    subTitle: "Corindone con Asterismo",
    formula: "Al₂O₃:Ti",
    system: "Trigonale",
    hardness: 9,
    category: "Ossido",
    colorGradient: "from-blue-500/20 via-cyan-600/10 to-indigo-300/5",
    accentColor: "#60a5fa",
    scientificBasis: "Corindone (durezza 9 Mohs) che presenta il fenomeno dell'asterismo: una stella luminosa a 6 punte formata dalla riflessione della luce su microscopici aghi orientati di rutilo (TiO₂). Simboleggia la guida, il punto di riferimento e la speranza nella notte.",
    opticsPhysical: "Asterismo ottico a 6 raggi, durezza estrema (secondo solo al diamante).",
    tags: ["Asterismo", "Aghi di Rutilo", "Punto di Riferimento", "Corindone"]
  },
  {
    number: 18,
    roman: "XVIII",
    arcanaName: "La Luna",
    mineralName: "Selenite",
    subTitle: "Gesso Satinato",
    formula: "CaSO₄·2H₂O",
    system: "Monoclinico",
    hardness: 2,
    category: "Solfato",
    colorGradient: "from-slate-200/20 via-indigo-100/10 to-sky-300/5",
    accentColor: "#e2e8f0",
    scientificBasis: "Varietà di gesso satinato sfaldabile in lamine traslucide, formatasi per evaporazione di bacini acquatici. La sua struttura fibrosa riflette la luce indiretta creando riflessi lattiginosi che rappresentano la percezione dell'inconscio e la mutevolezza.",
    opticsPhysical: "Bassissima durezza (scalfibile con l'unghia), conduzione ottica a fibra naturale.",
    tags: ["Riflesso Lattiginoso", "Evaporite", "Mutevolezza", "Inconscio"]
  },
  {
    number: 19,
    roman: "XIX",
    arcanaName: "Il Sole",
    mineralName: "Quarzo Citrino",
    subTitle: "Quarzo Dorato",
    formula: "SiO₂ + Fe³⁺",
    system: "Trigonale",
    hardness: 7,
    category: "Silicato",
    colorGradient: "from-amber-400/20 via-yellow-500/10 to-orange-400/5",
    accentColor: "#fbbf24",
    scientificBasis: "Quarzo ad alta brillantezza cromatico-dorata dovuta a tracce di ferro trivalente in sostituzione tetraedrica. Trasmette calore, elevata trasmittanza luminosa diretta e stabilità termica senza opacità. Incarna la massima chiarezza e radianza.",
    opticsPhysical: "Elevata trasmittanza nel visibile, assenza di sfaldatura, lucentezza vitrea intensa.",
    tags: ["Massima Radianza", "Trasmittanza", "Chiarezza", "Energia Solare"]
  },
  {
    number: 20,
    roman: "XX",
    arcanaName: "Il Giudizio",
    mineralName: "Moldavite",
    subTitle: "Tettite d'Impatto Meteoritico",
    formula: "Vetro d'Impatto Cosmogenerato",
    system: "Vetro da Impatto Cosmetico",
    hardness: 5.5,
    category: "Tettite",
    colorGradient: "from-emerald-700/20 via-lime-900/10 to-teal-950/5",
    accentColor: "#4ade80",
    scientificBasis: "Nata dalla fusione istantanea e dal lancio ad alta quota di rocce terrestri colpite da un meteorite caduto 15 milioni di anni fa. Simboleggia la chiamata dall'alto, il risveglio extra-terrestre, la sintesi tra cielo e terra e la trasmutazione evolutiva.",
    opticsPhysical: "Superficie scolpita da aerodinamica di rientro, fluidità vetrosa con bolle di lechatelierite.",
    tags: ["Origine Meteoritica", "Risveglio", "Sintesi Cielo-Terra", "Tettite"]
  },
  {
    number: 21,
    roman: "XXI",
    arcanaName: "Il Mondo",
    mineralName: "Diamante",
    subTitle: "Carbonio Puro Covalente",
    formula: "C",
    system: "Cubico Coordinato",
    hardness: 10,
    category: "Elemento Nativo",
    colorGradient: "from-cyan-200/20 via-blue-300/10 to-purple-200/5",
    accentColor: "#38bdf8",
    scientificBasis: "La sostanza naturale più dura conosciuta (10 Mohs), formata da un reticolo tridimensionale perfetto di atomi di carbonio legati da legami covalenti equivalenti. Simboleggia la perfezione geometrica, la massima integrità e il compimento del ciclo.",
    opticsPhysical: "Massima durezza assoluta, elevatissimo indice di rifrazione (2.42), conducibilità termica record.",
    tags: ["Reticolo Covalente", "Durezza 10 Mohs", "Perfezione", "Compimento"]
  }
];
